# -*- coding: utf-8 -*-
{
    'name': 'Odoo v13 Training - Hospital Management',
    'version': '13.0.1.0.0',
    'category': 'Training',
    'summary': 'Complete Odoo v13 beginner-to-advanced training module covering models, views, ORM, security, inheritance, wizards, reports and APIs.',
    'author': 'SolBizTech / Training Demo',
    'website': 'https://solbiztech.com',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/sequence.xml',
        'data/master_data.xml',
        'views/menu_views.xml',
        'views/department_views.xml',
        'views/doctor_views.xml',
        'views/patient_views.xml',
        'views/appointment_views.xml',
        'views/inheritance_demo_views.xml',
        'wizard/bulk_assign_doctor_wizard_views.xml',
        'wizard/patient_status_wizard_views.xml',
        'report/patient_report.xml',
        'report/appointment_report.xml',
    ],
    'demo': ['demo/demo_data.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
